[build]
builder = "dockerfile"

[deploy]
startCommand = "pnpm start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.args]
NODE_ENV = "production"
